import {
  HeartPulse,
  Stethoscope,
  Brain,
  Bone,
  Flower,
  Baby,
  Sparkles,
  Ear,
  Activity,
  Droplet,
  Waves,
  Gauge,
  Ribbon,
  Scan,
  Microscope,
  FlaskConical,
  ShieldCheck,
  Clock,
  Home,
  Users,
  FileCheck2,
  Award,
  MapPin,
  Phone,
  Mail,
  Search,
  Calendar,
  Building2,
} from "lucide-react";

const icons = {
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  brain: Brain,
  bone: Bone,
  flower: Flower,
  baby: Baby,
  sparkles: Sparkles,
  ear: Ear,
  activity: Activity,
  droplet: Droplet,
  waves: Waves,
  gauge: Gauge,
  ribbon: Ribbon,
  scan: Scan,
  microscope: Microscope,
  "flask-conical": FlaskConical,
  "shield-check": ShieldCheck,
  clock: Clock,
  home: Home,
  users: Users,
  "file-check": FileCheck2,
  award: Award,
  "map-pin": MapPin,
  phone: Phone,
  mail: Mail,
  search: Search,
  calendar: Calendar,
  building: Building2,
};

export default function Icon({ name, className = "", size = 22, strokeWidth = 1.8 }) {
  const Cmp = icons[name] || Activity;
  return <Cmp className={className} size={size} strokeWidth={strokeWidth} />;
}

